### ISSUE TITLE
should create a shortened url fails

### ISSUE THREAD

**Issue by IAPark** [hacksu/kenthackenough#1]
1) API URL Shortener should create a shortened url:
     Uncaught TypeError: Cannot read property 'should' of undefined
      at Test.<anonymous> (/Users/isaac/Documents/hacksu/kenthackenough/test/test.js:303:24)
      at Test.assert (/Users/isaac/Documents/hacksu/kenthackenough/node_modules/supertest/lib/test.js:221:6)
      at Server.assert (/Users/isaac/Documents/hacksu/kenthackenough/node_modules/supertest/lib/test.js:132:12)
      at Server.g (events.js:199:16)
      at Server.emit (events.js:104:17)
      at net.js:1392:10
      at process._tickCallback (node.js:355:11)

I'm not really sure what's causing this. Probably something I did when trying to install and setup libraries but I'm not sure.

**Comment by pdilyard** [comment]
Can't seem to replicate it. Do all the other tests pass on your machine?
If so, put the following before line 303 of test/test.js:
```javascript
console.log(res);
```
And then paste whatever it logs in here.

Thanks Isaac!

**Comment by IAPark** [comment]
Thanks. Now that I go to add a debug text (which was going to be my next step, but I had to do other things) it works. Go figure. Only thing I can guess is that it was a transient network issue as it seems that test relies on google.com? Though the email test would too? I don't know. Regardless it seems to be working now.

**Comment by pdilyard** [comment]
It doesn't actually rely on google, it just checks to see if you've redirected at all (that is, you get a 301 response). Anyway, it works :)
